### ISSUE TITLE
ListView: Bad move animations when data source is an array

### ISSUE THREAD

**Issue by rigdern** [winjs/angular-winjs#21]
### Impact

When you use an array as a data source and you move an item, all of the items in between the old index and new index fade out and then fade in as though they were removed and reinserted. Instead, those items should just slide into their new locations.

### Repro Steps

1. Paste the code below into an [Angular sample on the Try Site](http://try.buildwinjs.com/#angular:listview).
2. Click the "Move Item" button

**Expected:** Items below the moved item slide into place.

**Actual:** Items below the moved item fade out and fade in as though they were removed and reinserted.

```js
// JavaScript

angular.module('sample', ['winjs']).controller("sampleController", function ($scope) {
    $scope.items = [
        { title: "Marvelous Mint", text: "Gelato", picture: "/images/fruits/60Mint.png" },
        { title: "Succulent Strawberry", text: "Sorbet", picture: "/images/fruits/60Strawberry.png" },
        { title: "Banana Blast", text: "Low-fat frozen yogurt", picture: "/images/fruits/60Banana.png" },
        { title: "Lavish Lemon Ice", text: "Sorbet", picture: "/images/fruits/60Lemon.png" },
        { title: "Creamy Orange", text: "Sorbet", picture: "/images/fruits/60Orange.png" },
        { title: "Very Vanilla", text: "Ice Cream", picture: "/images/fruits/60Vanilla.png" },
        { title: "Banana Blast", text: "Low-fat frozen yogurt", picture: "/images/fruits/60Banana.png" },
        { title: "Lavish Lemon Ice", text: "Sorbet", picture: "/images/fruits/60Lemon.png" }
    ];

    $scope.moveItem = function () {
        WinJS.Utilities._slowAnimations = true;
        var item = $scope.items[1];
        $scope.items.splice(1, 1);
        $scope.items.splice(3, 0, item);
    };
});
```

```css
/* CSS */

/* Template for the items in the ListViews in this sample */       
.smallListIconTextItem
{
    width: 100%;
    height: 70px;
    padding: 5px;
    overflow: hidden;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
}

.smallListIconTextItem img.smallListIconTextItem-Image 
{
    width: 60px;
    height: 60px;
    margin: 5px;
    margin-right:20px;
}

.smallListIconTextItem .smallListIconTextItem-Detail
{
    margin: 5px;
}

.app {
    height: 100%;
}

/* CSS applied to the ListViews in this sample */
.listView
{
    height: 90%;
}

/* Override the background color for even/odd win-containers */
.listView .win-container.win-container-odd {
    background-color: #777;
}

.listView .win-container.win-container-even {
    background-color: #444;
}
```

```html
<!-- HTML -->

<div class="app" ng-app="sample" ng-controller="sampleController">
    <button ng-click="moveItem()">Move Item</button>
    <win-list-view class="listView win-selectionstylefilled"
                   item-data-source="items"
                   header="select('.header')">
        <win-item-template>
            <div class="smallListIconTextItem">
                <img src="{{item.data.picture}}" class="smallListIconTextItem-Image" />
                <div class="smallListIconTextItem-Detail">
                    <h4>{{item.data.title}}</h4>
                    <h6>{{item.data.text}}</h6>
                </div>
            </div>
        </win-item-template>
        <win-list-layout></win-list-layout>
    </win-list-view>
</div>
```
